### ISSUE TITLE
Probabilidades

### ISSUE THREAD

**Issue by lizllanos** [CIAT-DAPA/usaid_forecast_web#24]
Cambiar nombre de categoría "Normal" por "Cerca a lo normal", dado que se puede dar confusión con la climatología

**Comment by stevensotelo** [comment]
@lizllanos  este issue se encuentra duplicado con una sugerencia que realizo Armando #16 . Por favor indicarme entonces cual debería ser el título correcto.

**Comment by lizllanos** [comment]
El título debería ser "Cerca a lo normal"

**Comment by stevensotelo** [comment]
Solucionado en el commit 8435b57
