### ISSUE TITLE
Títulos probabilidades

### ISSUE THREAD

**Issue by lizllanos** [CIAT-DAPA/usaid_forecast_web#29]
Los títulos de las probabilidades deberían ser el trimestre, por ejemplo Marzo equivale al trimestre Febrero-Marzo-Abril

**Comment by stevensotelo** [comment]
@lizllanos y como sería para los meses siguientes?

**Comment by lizllanos** [comment]
@stevensotelo lo otro que se puede hacer es poner una nota aclaratoria que el mes que se menciona es el central del trimestre, creo que quedaría mejor

**Comment by stevensotelo** [comment]
@lizllanos Por favor me indicas cual debería ser la nota que se debe mostrar para aclarar el concepto.

**Comment by lizllanos** [comment]
Tener en cuenta que el mes que se muestra, es el central del trimestre a pronosticar. Por ejemplo: si el mes es Marzo, el trimestre que se usó para la predicción fue Febrero-Marzo-Abril
