### ISSUE TITLE
Condicionales para cuando no haya predicción

### ISSUE THREAD

**Issue by lizllanos** [CIAT-DAPA/usaid_forecast_web#30]
Debemos generar un warning al usuario cuando el desempeño del modelo no se óptimo (goodness index<0.1) y cuando las probabilidades no sean concluyentes (cuando las 3 categorias sean similares). Este warning debe decirle al usuario que no hay predicción y que se guíe por la climatología del mes.

**Comment by stevensotelo** [comment]
@dagudelo30 esta preparando un texto para este issue
