### ISSUE TITLE
15 días de pronóstico

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/usaid_forecast_web#39]
@lizllanos y @Jeikosd 

- [x] Para el proceso de remuestreo adicionar 1 mes antes de la fecha de inicio de pronostico
- [x] Modificar el start simulation para los modelos de arroz y maíz 

By @jramirezv

**Comment by lizllanos** [comment]
Ya esta lista la parte de clima en el pronóstico

**Comment by stevensotelo** [comment]
Solucionado en el proceso automático de la interfaz
