### ISSUE TITLE
pronosticos agroclimaticos

### ISSUE THREAD

**Issue by fannyhowland** [CIAT-DAPA/usaid_forecast_web#52]
- [x] para maíz, no está l;a escala de color: bajo/regular, normal... 

- [x] considerer poner ek rango de rendimiento correspondiendo a la escala de color

- [x] no aparece nada en la casilla de textura.

- [x] se debería poner en más grande las instrucciones de elegir textura de suelo. y poner instrucciones en más grande:

**Comment by stevensotelo** [comment]
Ya se adicionaron todos los cambios
