### ISSUE TITLE
la pagina en general

### ISSUE THREAD

**Issue by fannyhowland** [CIAT-DAPA/usaid_forecast_web#53]
- [ ] al modificar el tamaño de la ventana se sobreponen las imagines. solo se corige refrescando la pagina. pero al hacer esto , siempre se regresa sobre el inicio.

**Comment by stevensotelo** [comment]
Aunque las imagenes se se ajustan a las distintas pantallas, no es completamente responsive. Para que las imagenes se rendericen es necesario conocer el tamaño de la página.
