### ISSUE TITLE
Ajustar graficas de pronóstico de rendimiento: 

### ISSUE THREAD

**Issue by fannyhowland** [CIAT-DAPA/usaid_forecast_web#62]
* [x] líneas de franja roja punteada
* [x] cambiar color rojo en verde más claro
* [x] añadir el total a los indicadores
* [x] añadir texto para explicar las franjas

**Comment by stevensotelo** [comment]
Todos los requerimientos fueron resueltos en el commit 889ba03.

El punto 1 no se atendido dado que el segundo punto lo reemplazo
