### ISSUE TITLE
graficas de clima/ rendimiento

### ISSUE THREAD

**Issue by fannyhowland** [CIAT-DAPA/usaid_forecast_web#70]
- [x] poner la radacion solar en cm2/día

- [x] poner una decimal a los promedios historicos de temperature minima

- [x] poner el codigo IDEAM de las estaciones meteo

- [ ] poner fecha de germinacion en vez de fecha de siembra

- [x] hacer un tutorial para la grafica de nivel de confianza del pronostico

- [x] asegurarse de la Buena visibilidad de los logos de los socios

**Comment by stevensotelo** [comment]
- [x] poner la radacion solar en cm2/día
R// Se cambio la unidad de medida en radiación solar
- [x] hacer un tutorial para la grafica de nivel de confianza del pronostico
R// Se adiciona la opción de colocar tutoriales
- [x] asegurarse de la Buena visibilidad de los logos de los socios
R// Los logos ya estan incluidos en la página web
- [x] poner el codigo IDEAM de las estaciones meteo
R// Se adiciono el código externo a la visualización
- [x] poner una decimal a los promedios historicos de temperature minima
R// Armando recomienda mostrar los datos sin decimales

**Comment by stevensotelo** [comment]
@Leonard1984 y @jrodriguez88 

Ustedes que consideran sobre este punto:

- [x] poner fecha de germinacion en vez de fecha de siembra

**Comment by Leonard1984** [comment]
La germinacion es un proceso que ocurre bajo el suelo y que depende de la invivision de las semillas, por eso no se puede evaluar cuando germina una planta.  Las dos unicas posibilidades son fecha de siembra y fecha de emergencia, pero esta ultima es una medida subjetiva de cuando el observador cree que el 50% del lote ya germino, lo cual lo hace inexacto; es por eso que me parece prudente que nos quedemos con fecha de siembra.

saludos

**Comment by stevensotelo** [comment]
Gracias @Leonard1984
