### ISSUE TITLE
Regla validación para ejecución de CPT

### ISSUE THREAD

**Issue by aesquivel94** [CIAT-DAPA/usaid_forecast_web#74]
Para estos valores de entrada crea por favor una regla de validación para y_modes - cca_modes donde verifiques que el valor no sea mayor que el número de estaciones. En caso de que lo sea... por defecto podrías no se mandar un mensaje de error o darle el valor de 5 para y_modes, y para cca_modes 3.

**Comment by stevensotelo** [comment]
Esta regla ha sido incluida en el manual de usuario.
